version: '2.4'

services:
  vnu:
    image: ghcr.io/validator/validator:latest
    restart: always
  w3c:
    build: .
    image: ghcr.io/netresearch/validator-w3c
    ports:
     - "80:80"
    restart: always
    links:
     - vnu:vnu

