version: '3.5'

services:
  vnu:
    image: ghcr.io/validator/validator:latest
    restart: unless-stopped

  w3c:
    build: .
    image: ghcr.io/netresearch/validator-w3c
    ports:
     - "80:80"
    restart: unless-stopped
