# Bake definition for ghcr.io/netresearch/validator-w3c.
#
# Driven by netresearch/.github .github/workflows/build-container-bake.yml,
# which appends the tag + label bake files generated by docker/metadata-action
# to this file and then builds the `app` target.
#
# No `platforms` is declared on purpose: the image has always been built for
# the runner's native platform only (linux/amd64). Adding a platform list here
# would silently turn every publish into a multi-arch build.

# Placeholder replaced at build time by docker/metadata-action's generated
# bake definition (tags + labels). Do NOT hardcode tags on the target that
# inherits from it — the generated definition supplies them.
target "docker-metadata-action" {}

target "app" {
  inherits   = ["docker-metadata-action"]
  context    = "."
  dockerfile = "Dockerfile"
}

group "default" {
  targets = ["app"]
}
